### ISSUE TITLE
Add missing favicon.ico

### ISSUE THREAD

**Issue by hloeung** [canonical-web-and-design/assets.ubuntu.com#152]
Hi,

Can we add the missing favicon or a 301 permanent redirect to one?

```
$ curl -I https://assets.ubuntu.com/favicon.ico
HTTP/2 404
server: nginx/1.14.0 (Ubuntu)
date: Fri, 01 May 2020 21:59:17 GMT
content-type: application/json
allow: GET, HEAD, OPTIONS
x-cache: MISS from juju-prod45-ubuntu-assets-machine-10
x-cache-lookup: MISS from juju-prod45-ubuntu-assets-machine-10:80
via: 1.1 juju-prod45-ubuntu-assets-machine-10 (squid/3.3.8)

```
Thanks.

**Comment by nottrobin** [comment]
Oh sorry @Albert-Arthur actually this one won't be that easy. I can think of a way to hack it, but you'd definitely need my help, at least for the secrets. Ping me if you wanna give this a go.

**Comment by Albert-Arthur** [comment]
This was done with a redirect:
`curl -I https://assets.ubuntu.com/favicon.ico`
`HTTP/2 302 `
`server: nginx/1.14.0 (Ubuntu)`
`date: Mon, 22 Jun 2020 10:59:58 GMT`
`content-type: text/html; charset=utf-8`
`content-length: 0`
`location: https://assets.ubuntu.com/v1/49a1a858-favicon-32x32.png`
`allow: GET, HEAD, OPTIONS`
`cache-control: max-age=60`
`age: 14`
`x-cache: HIT from juju-prod45-ubuntu-assets-machine-9`
`x-cache-lookup: HIT from juju-prod45-ubuntu-assets-machine-9:80`
`via: 1.1 juju-prod45-ubuntu-assets-machine-9 (squid/3.3.8)`
`x-cache-status: MISS from content-cache-1ss/1` 

It was the quickest way to fix it until this (https://github.com/canonical-web-and-design/master-epics/issues/18) gets done.
