### ISSUE TITLE
Tags searching

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/assets.ubuntu.com#58]
- Store comma-separated tags as an array rather than a string in mongodb
- Store unique tags in a new "tags" mongodb collection (for future development possibilities)
- Work out how to migrate existing tags strings to be arrays
- Add a method for searching by tag (`/v1/?tag={tag}` probably)

**Comment by sowasred2012** [comment]
@goulinkh @nottrobin any thoughts on this?

**Comment by goulinkh** [comment]
@sowasred2012 We can add this to the new version of asset which is on the branch `assets_flask`, once it's deployed and replaces the current version of assets. As we cannot deploy changes to the current version of assets.

**Comment by nottrobin** [comment]
@goulinkh what is the data model for the new system like? Because this switch over seems like the perfect opportunity to make this change (from tag strings to proper relational tags)

**Comment by goulinkh** [comment]
@nottrobin All the metadata of an asset are in a field [called data](https://github.com/canonical-web-and-design/assets.ubuntu.com/blob/assets_flask/webapp/models.py#L20) of type `JSON`, so for tags it's a string inside of data: `"data": {tags: "tag1, tag2"}`
