### ISSUE TITLE
Move the assets server to Kubernetes

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/assets.ubuntu.com#80]
For ubuntu.com:
Compressing resources with gzip or deflate can reduce the number of bytes sent over the network.

Enable compression for the following resources to reduce their transfer size by 13.6KiB (65% reduction).
- Compressing https://assets.ubuntu.com/v1/3aac5c8c-servers.svg could save 6.5KiB (79% reduction).
- Compressing https://assets.ubuntu.com/v1/473ea07f-icon-intro-iot.svg could save 1.5KiB (63% reduction).
- Compressing https://assets.ubuntu.com/v1/949bb7ae-icon-intro-server.svg could save 1.3KiB (60% reduction).
- Compressing https://assets.ubuntu.com/v1/b066f89f-ibm-logo.svg could save 1.3KiB (56% reduction).
- Compressing https://assets.ubuntu.com/v1/e1b12fdd-external-link-9fa097.svg could save 953B (53% reduction).
- Compressing https://assets.ubuntu.com/v1/f24a8aa0-external-link-orange.svg could save 862B (51% reduction).
- Compressing https://assets.ubuntu.com/v1/12387180-navigation-menu-plain.svg could save 719B (57% reduction).
- Compressing https://assets.ubuntu.com/v1/9d395bdc-picto-startfirst-white.svg could save 536B (45% reduction).

**Comment by nottrobin** [comment]
This is not about compressing SVGs in general. I don't think SVG compression is worth much as an SVG is only a text file anyway. It's about enabling [HTTP compression](https://en.wikipedia.org/wiki/HTTP_compression).

The [Kubernetes Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) will enable gzip compression where appropriate by default, so at this point the best way to solve this is to switch the assets server over to Kubernetes.

**Comment by tbille** [comment]
Duplicate https://github.com/canonical-web-and-design/master-epics/issues/18
